# Generated by Django 3.1.7 on 2021-04-07 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapps', '0002_auto_20210407_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='skills',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
