# Generated by Django 3.1.7 on 2021-04-14 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapps', '0003_jobpost_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
