# Generated by Django 3.1.7 on 2021-04-14 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapps', '0004_jobpost_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='company_logo',
            field=models.ImageField(null=True, upload_to='%y/%m/%d'),
        ),
    ]
