# Generated by Django 3.1.7 on 2021-04-14 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapps', '0005_jobpost_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='education',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
