# Generated by Django 3.1.7 on 2021-04-14 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapps', '0006_jobpost_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='company_logo',
            field=models.ImageField(null=True, upload_to='photos/logo/%y/%m/%d'),
        ),
    ]
