# Generated by Django 3.1.7 on 2021-04-14 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapps', '0008_applyforjob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applyforjob',
            name='job_id',
        ),
        migrations.RemoveField(
            model_name='applyforjob',
            name='user',
        ),
    ]
