# Generated by Django 3.1.7 on 2021-04-14 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobapps', '0010_auto_20210414_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyforjob',
            name='job_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobapps.jobpost'),
        ),
        migrations.AddField(
            model_name='applyforjob',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='applyforjob',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
