# Generated by Django 3.1.7 on 2021-04-07 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekers',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
