# Generated by Django 3.1.7 on 2021-04-06 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210406_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeers',
            name='contact',
            field=models.IntegerField(blank=True, max_length=12, null=True),
        ),
    ]
