# Generated by Django 3.1.7 on 2021-04-07 08:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210407_0702'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeers',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobseekers',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobseekers',
            name='image',
            field=models.ImageField(blank=True, default=1, upload_to='photos/%y/%m/%d'),
            preserve_default=False,
        ),
    ]
