# Generated by Django 3.1.7 on 2021-04-07 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210407_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeers',
            name='contact',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
